### ISSUE TITLE
Reset tasks count for states that are no longer desired.

### ISSUE THREAD

**Issue by chrhicks** [flowcommerce/delta#253]
## Assumptions
- Current desired state of **0.2.58**
- Delta is automatically tagging and scaling
- 4 EC2 instances are backing the project cluster
- 2 instances are used per scales state / running version of the project

## Steps to reproduce

1. Merge to master. **0.2.59** is tagged and a docker image is building
1. Wait for delta to issue scale up of **0.2.59**
1. Merge to master again before scaling task for **0.2.59** is complete. **0.2.60** is tagged and a docker image is building
1. Wait for delta to issue scale up of **0.2.60**
1. Merge to master again before scaling task for **0.2.60** is complete. **0.2.61** is tagged.

At this point the _current state_ is still **0.2.58**. Current state is **0.2.60**. ECS has three versions of the project set to run 2 tasks each totaling 6.

- **0.2.58** is taking up 2 instances
- **0.2.59** is taking up 2 instances
- **0.2.60** has no resources available.

The project is now stuck and will never successfully scale new states.

## Expected behavior

Delta automatically scales down any services that are not the desired state or the current state.

**Comment by mbryzek** [comment]
Should be addressed in https://github.com/flowcommerce/delta/pull/256
